{
    "name": "CRM Extension",
    "version": "1.0",
    "depends": ['base','account','sale_management','utm','crm'],
    "author": "Qnomix Technologies",
    "category": "CRM",
    "sequence": -100,
    "summary": "",
    "data": [
        'security/ir.model.access.csv',
        'security/res_group.xml',
        'data/system_parameters.xml',
        'views/res_partner_inherit.xml',
        'views/sap_warehouse_views.xml',
        'views/sap_taxes_views.xml',
        'views/res_company_inherit.xml',
        'views/account_tax_inherit.xml',
        'views/api_log_views.xml',
        'views/customer_group_form.xml',
        'views/customer_series.xml',
        'views/sap_payment_terms.xml',
        'views/payment_terms_inherit.xml',
        'views/product_template.xml',
        'views/sale_order.xml',
        'views/menu.xml',
        'views/hide_menu.xml',
        'views/sap_delivery_view.xml',
        'views/sap_credit_note_view.xml',
        'views/sap_invoice_view.xml',
        'views/sap_payment_view.xml',
        'views/crm_lead_inherit_view.xml',
    ],
    "license": 'LGPL-3',
}
