from odoo import models, fields, api


class SnapdealPaymentReport(models.Model):
    _name = "snapdeal.payment.report"

    transaction_date = fields.Date(string="Transaction Date")
    seller_code = fields.Char(string="Seller Code")
    type = fields.Char(string="Type")
    transaction_id = fields.Float(string="Transaction ID")
    reason = fields.Char(string="Reason")
    name = fields.Char(string="Name")
    sku = fields.Char(string="SKU")
    invoice_number = fields.Char(string="Invoice Number")
    web_sale_price = fields.Float(string="Web Sale Price")
    payment_received_by_snapdeal = fields.Float(string="Payment Received By Snapdeal")
    seller_funded_cashback = fields.Float(string="Seller Funded Cashback")
    cash_discount = fields.Float(string="Cash Discount")
    cash_discount_adjustment = fields.Float(string="Cash Discount Adjustment")
    benefit_passed_on_to_buyer = fields.Float(string="Benefit Passed On To Buyer")
    emi = fields.Float(string="EMI")
    subvention_charges = fields.Float(string="Subvention Charges (Seller contribution)")
    fulfillment_fee = fields.Float(string="Fulfillment Fee")
    fulfillment_fee_waiver = fields.Float(string="Fulfillment Fee Waiver")
    processing_charges = fields.Float(string="Processing Charges")
    packaging_charges = fields.Float(string="Packaging Charges")
    special_packaging_charges = fields.Float(string="Special packaging Charges")
    marketing_fee = fields.Float(string="Marketing Fee")
    closing_fee = fields.Float(string="Closing Fee")
    payment_collection_fee = fields.Float(string="Payment Collection Fee")
    courier_fee = fields.Float(string="Courier Fee")
    fulfilment_fees_for_returns = fields.Float(string="Fulfilment Fees For Returns")
    processing_fees_for_returns = fields.Float(string="Processing Fees For Returns")
    packaging_fees_for_returns = fields.Float(string="Packaging Fees For Returns")
    special_packaging_fees_for_returns = fields.Float(string="Special Packaging Fees For Returns")
    payment_collection_fees_for_returns = fields.Float(string="Payment Collection Fees For Returns")
    logistics_fees_for_returns = fields.Float(string="Logistics Fees For Returns")
    reverse_logistics_fees_for_returns = fields.Float(string="Reverse Logistics Fees for Returns")
    service_tax = fields.Float(string="Service Tax")
    swachh_bharat_cess = fields.Float(string="Swachh Bharat Cess")
    krishi_kalyan_cess = fields.Float(string="Krishi Kalyan Cess")
    sgst = fields.Float(string="SGST")
    cgst = fields.Float(string="CGST")
    utgst = fields.Float(string="UTGST")
    igst  = fields.Float(string="IGST")
    commission = fields.Float(string="Commission")
    netpayable = fields.Float(string="NetPayable")
    payment_date = fields.Date(string="Payment Date")
    settlement_ref_id = fields.Char(string="Settlement Ref Id")
    order_creation_date = fields.Date(string="Order Creation Date")
    delivered_date = fields.Date(string="Delivered Date")
    awb_number = fields.Char(string="AWB Number")
    shipped_return_date = fields.Date(string="Shipped Return Date")
    courier_name = fields.Char(string="Courier Name")
    fulfilment_mode = fields.Char(string="Fulfilment Mode")
    customer_name = fields.Char(string="Customer Name")
    customer_city = fields.Char(string="Customer City")
