{
    'name': 'Equipment Management System',
    "license": 'LGPL-3',
    "depends": ['base', 'mail'],
    "author": "Qnomix Technologies",
    "data": [
        'security/equipment_access.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'data/unit_utilization_data.xml',
        'wizards/draft_wizard_view.xml',
        # 'report/machinery_porgress_layout.xml',
        'views/hide_menu.xml',
        'views/equipment_master.xml',
        'views/equipment_type.xml',
        # 'views/equipment_name.xml',
        'views/equipment_purpose.xml',
        # 'views/hired_equipment_type.xml',
        'views/equipment_model.xml',
        'views/equipment_maker.xml',
        'views/equipment_capacity.xml',
        'views/unit_utilization.xml',

        'views/res_users_views.xml',
        'views/project_master.xml',
        'views/devision_master.xml',
        'views/plant_maker.xml',
        'views/plant_model.xml',
        'views/plant_capacity.xml',
        'views/plant_category.xml',
        'views/maker_master_name.xml',
        'views/plant_master.xml',
        'views/machinery_progress.xml',
        'views/machinery_progress_line.xml',
        'views/assign_equipment_view.xml',
        'views/menuitem.xml',
    ]
}